# editoverwrites extension for the Datenstrom Yellow CMS 

Extension: editoverwrites
Version: 0.9.1
Status: experimental
Description: consistent look and feel for the editor that appears the same in all themes, developed using the ibbtown theme.
DocumentationUrl: https://github.com/PetersOtto/yellow-EditOverwrites
DownloadUrl: https://github.com/PetersOtto/yellow-EditOverwrites/archive/refs/heads/main.zip
Published: 2026-04-16 23:55:00
Designer: PetersOtto
Tag: Edit, Editor, css, overwrites

system/workers/editoverwrites.php: editoverwrites.php, create, update
system/themes/editoverwrites/css/editoverwrites.min.css: editoverwrites.min.css, create, update, careful
system/themes/editoverwrites/css/editoverwrites.min.css.map: editoverwrites.min.css.map, create, update, careful
system/themes/editoverwrites/scss/editoverwrites.scss: editoverwrites.scss, create, update, careful
